[project]
name = "icloud-drive-uploader"
version = "0.1.0"
description = "A Python tool for recursively uploading local folders to iCloud Drive with secure authentication"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyicloud>=2.0.1",
]
